-- 158 검진 판정표 v1.2 — 국가건강검진 판정기준(고시 2026-6호) 단일 기준 · 생성: tools/gen_biomarker_map_v1_2.py
-- 평가: IP/integration/checkup_ranges_v1_2_eval.md · 바뀜: 라벨(참고범위 내/높음/낮음/의료진 상담 권장) · AST/ALT/감마GTP/혈색소/BMI/크레아티닌 기준 · 하한·상한 꼬리 · 신규 3항목(이완기혈압·허리둘레·eGFR)
-- 판정 범위 테이블만 교체(사용자 기록·값 무관). 다시 실행해도 같은 결과.
begin;
insert into public.biomarker_rules (biomarker_key, display_name_ko, unit, category_group, inverted, note, schema_version) values
('HbA1c', '당화혈색소', '%', '당대사', false, null, '1.2.0'),
('fasting_glucose', '공복혈당', 'mg/dL', '당대사', false, null, '1.2.0'),
('total_cholesterol', '총콜레스테롤', 'mg/dL', '지질대사', false, null, '1.2.0'),
('LDL', 'LDL 콜레스테롤', 'mg/dL', '지질대사', false, null, '1.2.0'),
('HDL', 'HDL 콜레스테롤', 'mg/dL', '지질대사', true, 'HDL은 높을수록 좋음 - 역방향 해석', '1.2.0'),
('triglyceride', '중성지방', 'mg/dL', '지질대사', false, null, '1.2.0'),
('blood_pressure_systolic', '수축기혈압', 'mmHg', '혈압', false, null, '1.2.0'),
('blood_pressure_diastolic', '이완기혈압', 'mmHg', '혈압', false, null, '1.2.0'),
('AST', 'AST (간기능)', 'U/L', '간기능', false, null, '1.2.0'),
('ALT', 'ALT (간기능)', 'U/L', '간기능', false, null, '1.2.0'),
('GGT', '감마GTP', 'U/L', '간기능', false, null, '1.2.0'),
('creatinine', '크레아티닌', 'mg/dL', '신장기능', false, '신장은 기능성 원료 인정 항목 없음 - 추천 비활성', '1.2.0'),
('egfr', 'eGFR(신사구체여과율)', 'mL/min/1.73m²', '신장기능', true, '높을수록 좋음 - 결과지에 없으면 크레아티닌으로 추정', '1.2.0'),
('BMI', '체질량지수', 'kg/m²', '체중관리', false, null, '1.2.0'),
('waist', '허리둘레', 'cm', '체중관리', false, null, '1.2.0'),
('hemoglobin', '혈색소', 'g/dL', '빈혈', true, 'low일수록 빈혈', '1.2.0'),
('TSH', '갑상선자극호르몬', 'mIU/L', '갑상선', false, '갑상선은 기능성 원료 인정 항목 없음 - 추천 비활성', '1.2.0'),
('vitamin_D', '비타민 D', 'ng/mL', '영양상태', false, null, '1.2.0')
on conflict (biomarker_key) do update set display_name_ko = excluded.display_name_ko, unit = excluded.unit, category_group = excluded.category_group, inverted = excluded.inverted, note = excluded.note, schema_version = excluded.schema_version;
delete from public.biomarker_ranges where biomarker_key in ('HbA1c', 'fasting_glucose', 'total_cholesterol', 'LDL', 'HDL', 'triglyceride', 'blood_pressure_systolic', 'blood_pressure_diastolic', 'AST', 'ALT', 'GGT', 'creatinine', 'egfr', 'BMI', 'waist', 'hemoglobin', 'TSH', 'vitamin_D');
insert into public.biomarker_ranges (biomarker_key, range_min, range_max, level, label_ko, functional_needs, tone, force_medical_referral, sex_specific, sort_order) values
('HbA1c', 0, 5.7, 'normal', '참고범위 내', '{}', '유지', false, null, 1),
('HbA1c', 5.7, 6.5, 'watch', '참고범위보다 높음', '{혈당조절}', '관리권장', false, null, 2),
('HbA1c', 6.5, 99, 'high', '의료진 상담 권장', '{혈당조절}', '전문가상담권장', true, null, 3),
('fasting_glucose', 0, 70, 'low', '의료진 상담 권장', '{}', '전문가상담권장', true, null, 1),
('fasting_glucose', 70, 100, 'normal', '참고범위 내', '{}', '유지', false, null, 2),
('fasting_glucose', 100, 126, 'watch', '참고범위보다 높음', '{혈당조절}', '관리권장', false, null, 3),
('fasting_glucose', 126, 999, 'high', '의료진 상담 권장', '{혈당조절}', '전문가상담권장', true, null, 4),
('total_cholesterol', 0, 200, 'normal', '참고범위 내', '{}', '유지', false, null, 1),
('total_cholesterol', 200, 240, 'watch', '참고범위보다 높음', '{콜레스테롤개선}', '관리권장', false, null, 2),
('total_cholesterol', 240, 999, 'high', '의료진 상담 권장', '{콜레스테롤개선}', '전문가상담권장', true, null, 3),
('LDL', 0, 130, 'normal', '참고범위 내', '{}', '유지', false, null, 1),
('LDL', 130, 160, 'watch', '참고범위보다 높음', '{콜레스테롤개선,혈중중성지방개선}', '관리권장', false, null, 2),
('LDL', 160, 999, 'high', '의료진 상담 권장', '{콜레스테롤개선}', '전문가상담권장', true, null, 3),
('HDL', 0, 40, 'low', '의료진 상담 권장', '{혈행개선}', '전문가상담권장', true, null, 1),
('HDL', 40, 60, 'watch', '참고범위보다 낮음', '{혈행개선}', '관리권장', false, null, 2),
('HDL', 60, 999, 'normal', '참고범위 내', '{}', '유지', false, null, 3),
('triglyceride', 0, 150, 'normal', '참고범위 내', '{}', '유지', false, null, 1),
('triglyceride', 150, 200, 'watch', '참고범위보다 높음', '{혈중중성지방개선}', '관리권장', false, null, 2),
('triglyceride', 200, 9999, 'high', '의료진 상담 권장', '{혈중중성지방개선}', '전문가상담권장', true, null, 3),
('blood_pressure_systolic', 0, 90, 'low', '참고범위보다 낮음', '{}', '관리권장', false, null, 1),
('blood_pressure_systolic', 90, 120, 'normal', '참고범위 내', '{}', '유지', false, null, 2),
('blood_pressure_systolic', 120, 140, 'watch', '참고범위보다 높음', '{혈압조절}', '관리권장', false, null, 3),
('blood_pressure_systolic', 140, 999, 'high', '의료진 상담 권장', '{혈압조절}', '전문가상담권장', true, null, 4),
('blood_pressure_diastolic', 0, 60, 'low', '참고범위보다 낮음', '{}', '관리권장', false, null, 1),
('blood_pressure_diastolic', 60, 80, 'normal', '참고범위 내', '{}', '유지', false, null, 2),
('blood_pressure_diastolic', 80, 90, 'watch', '참고범위보다 높음', '{혈압조절}', '관리권장', false, null, 3),
('blood_pressure_diastolic', 90, 999, 'high', '의료진 상담 권장', '{혈압조절}', '전문가상담권장', true, null, 4),
('AST', 0, 41, 'normal', '참고범위 내', '{}', '유지', false, null, 1),
('AST', 41, 51, 'watch', '참고범위보다 높음', '{간건강}', '관리권장', false, null, 2),
('AST', 51, 9999, 'high', '의료진 상담 권장', '{간건강}', '전문가상담권장', true, null, 3),
('ALT', 0, 36, 'normal', '참고범위 내', '{}', '유지', false, null, 1),
('ALT', 36, 46, 'watch', '참고범위보다 높음', '{간건강}', '관리권장', false, null, 2),
('ALT', 46, 9999, 'high', '의료진 상담 권장', '{간건강}', '전문가상담권장', true, null, 3),
('GGT', 0, 64, 'normal', '참고범위 내', '{}', '유지', false, 'M', 1),
('GGT', 64, 78, 'watch', '참고범위보다 높음', '{간건강}', '관리권장', false, 'M', 2),
('GGT', 78, 9999, 'high', '의료진 상담 권장', '{간건강}', '전문가상담권장', true, 'M', 3),
('GGT', 0, 36, 'normal', '참고범위 내', '{}', '유지', false, 'F', 4),
('GGT', 36, 46, 'watch', '참고범위보다 높음', '{간건강}', '관리권장', false, 'F', 5),
('GGT', 46, 9999, 'high', '의료진 상담 권장', '{간건강}', '전문가상담권장', true, 'F', 6),
('creatinine', 0, 1.51, 'normal', '참고범위 내', '{}', '유지', false, null, 1),
('creatinine', 1.51, 999, 'high', '의료진 상담 권장', '{}', '전문가상담권장', true, null, 2),
('egfr', 0, 60, 'low', '의료진 상담 권장', '{}', '전문가상담권장', true, null, 1),
('egfr', 60, 999, 'normal', '참고범위 내', '{}', '유지', false, null, 2),
('BMI', 0, 18.5, 'low', '참고범위보다 낮음', '{}', '관리권장', false, null, 1),
('BMI', 18.5, 25, 'normal', '참고범위 내', '{}', '유지', false, null, 2),
('BMI', 25, 30, 'watch', '참고범위보다 높음', '{체지방감소}', '관리권장', false, null, 3),
('BMI', 30, 999, 'high', '의료진 상담 권장', '{체지방감소}', '전문가상담권장', true, null, 4),
('waist', 0, 90, 'normal', '참고범위 내', '{}', '유지', false, 'M', 1),
('waist', 90, 999, 'high', '의료진 상담 권장', '{체지방감소}', '전문가상담권장', true, 'M', 2),
('waist', 0, 85, 'normal', '참고범위 내', '{}', '유지', false, 'F', 3),
('waist', 85, 999, 'high', '의료진 상담 권장', '{체지방감소}', '전문가상담권장', true, 'F', 4),
('hemoglobin', 0, 12, 'low', '의료진 상담 권장', '{철분보충}', '전문가상담권장', true, 'M', 1),
('hemoglobin', 12, 13, 'low', '참고범위보다 약간 낮음', '{철분보충}', '관리권장', false, 'M', 2),
('hemoglobin', 13, 16.6, 'normal', '참고범위 내', '{}', '유지', false, 'M', 3),
('hemoglobin', 16.6, 18, 'watch', '참고범위보다 높음', '{}', '관리권장', false, 'M', 4),
('hemoglobin', 18, 99, 'high', '의료진 상담 권장', '{}', '전문가상담권장', true, 'M', 5),
('hemoglobin', 0, 10, 'low', '의료진 상담 권장', '{철분보충}', '전문가상담권장', true, 'F', 6),
('hemoglobin', 10, 12, 'low', '참고범위보다 약간 낮음', '{철분보충}', '관리권장', false, 'F', 7),
('hemoglobin', 12, 15.6, 'normal', '참고범위 내', '{}', '유지', false, 'F', 8),
('hemoglobin', 15.6, 17, 'watch', '참고범위보다 높음', '{}', '관리권장', false, 'F', 9),
('hemoglobin', 17, 99, 'high', '의료진 상담 권장', '{}', '전문가상담권장', true, 'F', 10),
('TSH', 0, 0.4, 'low', '의료진 상담 권장', '{}', '전문가상담권장', true, null, 1),
('TSH', 0.4, 4.51, 'normal', '참고범위 내', '{}', '유지', false, null, 2),
('TSH', 4.51, 999, 'high', '의료진 상담 권장', '{}', '전문가상담권장', true, null, 3),
('vitamin_D', 0, 20, 'low', '참고범위보다 낮음', '{비타민D보충}', '관리권장', false, null, 1),
('vitamin_D', 20, 30, 'watch', '참고범위보다 약간 낮음', '{비타민D보충}', '관리권장', false, null, 2),
('vitamin_D', 30, 100, 'normal', '참고범위 내', '{}', '유지', false, null, 3),
('vitamin_D', 100, 999, 'high', '의료진 상담 권장', '{}', '전문가상담권장', true, null, 4);
commit;

-- 확인 ① 행 수(기대: 항목 18 · 구간 68)
select (select count(*) from public.biomarker_rules) as rules, (select count(*) from public.biomarker_ranges) as ranges;
-- 확인 ② 틈·겹침 0행
select biomarker_key, sex_specific, range_max, next_min from (select biomarker_key, sex_specific, range_max, lead(range_min) over (partition by biomarker_key, coalesce(sex_specific,'') order by range_min) as next_min from public.biomarker_ranges) t where next_min is not null and next_min <> range_max;
